### ISSUE TITLE
Search for license plate in stolen car database

### ISSUE THREAD

**Issue by patcon** [f3ndot/my-bike-lane#11]
http://app.cpic-cipc.ca/English/searchformlic.cfm

OK, so this is mainly a silly/fun feature, but we could check to see whether a vehicle has been reported stolen. Since police won't enforce bike lane violations, we can at least entertain the small chance that we can nab the driver as engaging in "*real* criminal behaviour" :)

**Comment by borisplotkin** [comment]
I like it! run with it.

**Comment by f3ndot** [comment]
Although a fun idea, the website's form doesn't expose an API and uses a CSRF token. While there are workarounds for the CSRF on server-side processing, it doesn't make sense to fight something with it providing such a marginal benefit.
